export { defaultTheme, darkOverrides } from './defaultTheme'
export { createTheme } from './createTheme'
export { GlobalStyles } from './GlobalStyles'
export { BootstrapStyledProvider } from './Provider'
export type { BootstrapStyledProviderProps } from './Provider'
export type { Theme, ColorName, DeepPartial } from './types'
