// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4\"/>"

export const BsIconPlus = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconPlus(props, ref) {
  return <IconBase ref={ref} bsName="plus" svgInner={svgInner} {...props} />
})
BsIconPlus.displayName = "BsIconPlus"
