// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path fill-rule=\"evenodd\" d=\"M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708z\"/>"

export const BsIconChevronUp = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconChevronUp(props, ref) {
  return <IconBase ref={ref} bsName="chevron-up" svgInner={svgInner} {...props} />
})
BsIconChevronUp.displayName = "BsIconChevronUp"
