// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path fill-rule=\"evenodd\" d=\"M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0\"/>"

export const BsIconChevronLeft = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconChevronLeft(props, ref) {
  return <IconBase ref={ref} bsName="chevron-left" svgInner={svgInner} {...props} />
})
BsIconChevronLeft.displayName = "BsIconChevronLeft"
