// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path fill-rule=\"evenodd\" d=\"M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708\"/>"

export const BsIconChevronDown = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconChevronDown(props, ref) {
  return <IconBase ref={ref} bsName="chevron-down" svgInner={svgInner} {...props} />
})
BsIconChevronDown.displayName = "BsIconChevronDown"
