// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708\"/>"

export const BsIconX = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconX(props, ref) {
  return <IconBase ref={ref} bsName="x" svgInner={svgInner} {...props} />
})
BsIconX.displayName = "BsIconX"
