// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path fill-rule=\"evenodd\" d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708\"/>"

export const BsIconChevronRight = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconChevronRight(props, ref) {
  return <IconBase ref={ref} bsName="chevron-right" svgInner={svgInner} {...props} />
})
BsIconChevronRight.displayName = "BsIconChevronRight"
