// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '../IconBase'

const svgInner = "<path d=\"M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z\"/>"

export const BsIconCheck = React.forwardRef<SVGSVGElement, IconBaseProps>(function BsIconCheck(props, ref) {
  return <IconBase ref={ref} bsName="check" svgInner={svgInner} {...props} />
})
BsIconCheck.displayName = "BsIconCheck"
