#!/usr/bin/env node
// gen-icons.mjs — build-time codegen for Bootstrap Icons React components.
//
// Reads the vendored `bootstrap-icons` SVG set and emits, per icon, a
// self-contained tree-shakeable React component (`<BsIconAlarm/>`) plus a
// name→inner-SVG registry that backs the dynamic `<Icon name="…"/>`.
//
// Modes:
//   node scripts/gen-icons.mjs            → FULL set (2000+) → src/components/Icon/generated/
//                                           (git-ignored via generated/.gitignore; the build target)
//   node scripts/gen-icons.mjs --subset   → the committed representative subset → src/components/Icon/icons/
//                                           (hand-checked-in so tree-shakeable exports are real & testable now)
//
// The two outputs are byte-identical in shape; only the icon set differs.
// Path data is embedded verbatim (JSON-encoded) so rendered SVGs match the
// vendored source byte-for-byte on the `d` attributes.

import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(__dirname, '..')
const ICONS_SRC = resolve(REPO, 'node_modules/bootstrap-icons/icons')

// The representative subset committed to the repo (~12 common icons).
const SUBSET = [
  'alarm', 'check', 'x',
  'chevron-down', 'chevron-up', 'chevron-left', 'chevron-right',
  'house', 'gear', 'search', 'trash', 'plus', 'star',
  'twitter', 'instagram', 'facebook', 'github',
]

const isSubset = process.argv.includes('--subset')
const OUT_DIR = isSubset
  ? resolve(REPO, 'src/components/Icon/icons')
  : resolve(REPO, 'src/components/Icon/generated')
// per-icon modules live under ../IconBase relative to icons/, ../../IconBase from generated/? no:
// both icons/ and generated/ are direct children of Icon/, so IconBase is one level up.
const BASE_IMPORT = '../IconBase'

/** kebab/slug → PascalCase, prefixed BsIcon (always a valid identifier). */
function toComponentName(slug) {
  const pascal = slug
    .split(/[-_]/)
    .map((p) => (p ? p[0].toUpperCase() + p.slice(1) : ''))
    .join('')
  return `BsIcon${pascal}`
}

/** Extract { viewBox, inner } from a Bootstrap Icons SVG file. */
function parseSvg(svg) {
  const viewBoxMatch = svg.match(/viewBox="([^"]*)"/)
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 16 16'
  // inner = everything between the opening <svg …> and </svg>, trimmed.
  const openEnd = svg.indexOf('>')
  const closeStart = svg.lastIndexOf('</svg>')
  const inner = svg.slice(openEnd + 1, closeStart).trim()
  return { viewBox, inner }
}

function iconModuleSource(slug, comp, viewBox, inner) {
  const vb = viewBox === '0 0 16 16' ? '' : `\n    viewBox={${JSON.stringify(viewBox)}}`
  return `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
import * as React from 'react'
import { IconBase, type IconBaseProps } from '${BASE_IMPORT}'

const svgInner = ${JSON.stringify(inner)}

export const ${comp} = React.forwardRef<SVGSVGElement, IconBaseProps>(function ${comp}(props, ref) {
  return <IconBase ref={ref} bsName=${JSON.stringify(slug)} svgInner={svgInner}${vb} {...props} />
})
${comp}.displayName = ${JSON.stringify(comp)}
`
}

function run() {
  if (!existsSync(ICONS_SRC)) {
    console.error(`bootstrap-icons not found at ${ICONS_SRC} — run \`npm install\` first.`)
    process.exit(1)
  }

  let slugs = readdirSync(ICONS_SRC)
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.replace(/\.svg$/, ''))
    .sort()

  if (isSubset) {
    slugs = SUBSET.slice().sort()
  }

  // Fresh output dir.
  rmSync(OUT_DIR, { recursive: true, force: true })
  mkdirSync(OUT_DIR, { recursive: true })

  // For the git-ignored generated/ dir, drop a .gitignore so nothing is committed.
  if (!isSubset) {
    writeFileSync(join(OUT_DIR, '.gitignore'), '# Generated by scripts/gen-icons.mjs — not committed.\n*\n!.gitignore\n')
  }

  const registry = {}
  const barrelLines = []

  for (const slug of slugs) {
    const svg = readFileSync(join(ICONS_SRC, `${slug}.svg`), 'utf8')
    const { viewBox, inner } = parseSvg(svg)
    const comp = toComponentName(slug)
    writeFileSync(join(OUT_DIR, `${comp}.tsx`), iconModuleSource(slug, comp, viewBox, inner))
    barrelLines.push(`export { ${comp} } from './${comp}'`)
    registry[slug] = inner
  }

  // Barrel of per-icon exports.
  writeFileSync(
    join(OUT_DIR, 'index.ts'),
    `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n${barrelLines.join('\n')}\n`,
  )

  // Registry backing the dynamic <Icon name="…"/>.
  const registryEntries = Object.keys(registry)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(registry[k])},`)
    .join('\n')
  const registryPath = isSubset
    ? resolve(REPO, 'src/components/Icon/registry.ts')
    : join(OUT_DIR, 'registry.ts')
  writeFileSync(
    registryPath,
    `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// name → inner SVG markup, backing the dynamic <Icon name="…"/> convenience.
export const icons: Record<string, string> = {
${registryEntries}
}
`,
  )

  console.log(
    `gen-icons: ${slugs.length} icon(s) → ${OUT_DIR.replace(REPO + '/', '')}` +
      ` + registry ${registryPath.replace(REPO + '/', '')}`,
  )
}

run()
